services:
  backend:
    image: python:3.11
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "pip install --upgrade pip && pip install -r requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=fabbric.settings

    # make sure that the backend is running before the frontend starts
    healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:8000/admin || exit 1"]
        interval: 10s
        timeout: 5s
        retries: 5



  frontend:
    image: node:18
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "npm install && npm run build && npx serve -s build -l 3000"
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
